module.exports = [
    {
        name:'Liche',
        class:'Boss',
        health:50,
        weaknesses:'Fire',
        resistances:'Ice',
        attack1name:'Drain Vitality',
        attack1type:'Dark',
        attack1damage:8,
        attack2name:'Freeze Blood',
        attack2type:'Ice',
        attack2damage:8,
        xpReward:20,
        scoreReward:800,
    },
    // {
    //     name:'',
    //     class:'Boss',
    //     health:0,
    //     weaknesses:'',
    //     resistances:'',
    //     attack1name:'',
    //     attack1damage:0,
    //     attack2name:'',
    //     attack2damage:0,
    //     xpReward:0,
    //     scoreReward:0,
    // },
]