module.exports =  [
    {
        class:'Crusader',
        desc:``,
        health:25,
        attack1name:'Holy Blade',
        attack1damage:4,
        attack1type:'Slash',
        attack1cost:4,
        attack2name:'Holy Water',
        attack2damage:6,
        attack2type:'Holy',
        attack2cost:6,
    },
    {
        class:'Hunter',
        desc:``,
        health:22,
        attack1name:'Arrow Shot',
        attack1damage:5,
        attack1type:'Slash',
        attack1cost:4,
        attack2name:'Club',
        attack2damage:5,
        attack2type:'Blunt',
        attack2cost:4,
    },
    {
        class:'Mage',
        desc:``,
        health:20,
        attack1name:'Fireball',
        attack1damage:4,
        attack1type:'Fire',
        attack1cost:4,
        attack2name:'Ice Spike',
        attack2damage:4,
        attack2type:'Ice',
        attack2cost:4,
    },
    // {
    //     class:'',
    //     desc:``,
    //     health:0,
    //     attack1name:'',
    //     attack1damage:0,
    //     attack1type:'',
    //     attack1cost:0,
    //     attack2name:'',
    //     attack2damage:0,
    //     attack2type:'',
    //     attack2cost:0,
    // },
    
]