// Current Classes: Goblin, Beast, Spectre, Human,

// Current Attack Types: Slash, Blunt, Fire, Ice, Holy, Arcane, Poison, Heal, Block, Dark,

// Attack Types Used: Slash: 4 , Blunt: 3 , Fire: 4 , Ice: 3 , Holy: 3 , Arcane: 3 , Poison: 4 , Heal: 4 , Block: 3 , Dark: 4 ,

// Weaknesses: Slash: 3 , Blunt: 1 , Fire: 2, Ice: 0, Holy: 1, Arcane: 1, Poison: 3,  Dark: 0,

// Resistances: Slash: 2 , Blunt: 0 , Fire: 0, Ice: 3, Holy: 0, Arcane: 5, Poison: 1,  Dark: 0,

module.exports =  [
    {
        class:'Crusader',
        desc:``,
        health:50,
        attack1name:'Holy Blade',
        attack1damage:3,
        attack1type:'Slash',
        attack2name:'Holy Water',
        attack2damage:3,
        attack2type:'Holy',
    },
    {
        class:'Hunter',
        desc:``,
        health:45,
        attack1name:'Arrow Shot',
        attack1damage:3,
        attack1type:'Slash',
        attack2name:'Club',
        attack2damage:4,
        attack2type:'Blunt',
    },
    {
        class:'Wizard',
        desc:``,
        health:40,
        attack1name:'Fireball',
        attack1damage:4,
        attack1type:'Fire',
        attack2name:'Ice Spike',
        attack2damage:4,
        attack2type:'Ice',
    },
    {
        class:'Rogue',
        desc:``,
        health:45,
        attack1name:'Back-Stab',
        attack1damage:3,
        attack1type:'Slash',
        attack2name:'Poisoned-Stab',
        attack2damage:4,
        attack2type:'Poison',
    },
    {
        class:'Conjurer',
        desc:``,
        health:40,
        attack1name:'Arcane Bolt',
        attack1damage:4,
        attack1type:'Arcane',
        attack2name:'Arcane Spear',
        attack2damage:4,
        attack2type:'Slash',
    },
    {
        class:'Pyromancer',
        desc:``,
        health:40,
        attack1name:'Fire Spear',
        attack1damage:4,
        attack1type:'Slash',
        attack2name:'Immolate',
        attack2damage:4,
        attack2type:'Fire',
    },
    {
        class:'Priest',
        desc:``,
        health:40,
        attack1name:'Smite',
        attack1damage:4,
        attack1type:'Holy',
        attack2name:'Pray',
        attack2damage:5,
        attack2type:'Heal',
    },
    {
        class:'Black Knight',
        desc:``,
        health:50,
        attack1name:'Decapitate',
        attack1damage:3,
        attack1type:'Dark',
        attack2name:'Raise Shield',
        attack2damage:7,
        attack2type:'Block',
    },
    {
        class:'Diseased',
        desc:``,
        health:45,
        attack1name:'Spit Poison',
        attack1damage:4,
        attack1type:'Poison',
        attack2name:'Punch',
        attack2damage:4,
        attack2type:'Blunt',
    },
    {
        class:'Witch-Doctor',
        desc:``,
        health:40,
        attack1name:'Poison Toads',
        attack1damage:4,
        attack1type:'Poison',
        attack2name:'Herbal Medicine',
        attack2damage:6,
        attack2type:'Heal',
    },
    {
        class:'Ice Incarnate',
        desc:``,
        health:35,
        attack1name:'Ice Claw',
        attack1damage:4,
        attack1type:'Ice',
        attack2name:'Ice Sheet',
        attack2damage:5,
        attack2type:'Block',
    },
    {
        class:'Cultist',
        desc:``,
        health:25,
        attack1name:'Void Lance',
        attack1damage:8,
        attack1type:'Dark',
        attack2name:'Arcane Bow',
        attack2damage:8,
        attack2type:'Arcane',
    },
    {
        class:'Paladin',
        desc:``,
        health:60,
        attack1name:'Bash',
        attack1damage:3,
        attack1type:'Blunt',
        attack2name:'Heal Spell',
        attack2damage:6,
        attack2type:'Heal',
    },
    {
        class:'Demon Knight',
        desc:``,
        health:50,
        attack1name:'Void Blade',
        attack1damage:3,
        attack1type:'Dark',
        attack2name:'Fire Breath',
        attack2damage:3,
        attack2type:'Fire',
    },
    {
        class:'Living Puppet',
        desc:``,
        health:30,
        attack1name:'Spirit Bomb',
        attack1damage:6,
        attack1type:'Arcane',
        attack2name:'Restuff',
        attack2damage:6,
        attack2type:'Heal',
    },
    {
        class:'Ice Druid',
        desc:``,
        health:40,
        attack1name:'Ice Spear',
        attack1damage:4,
        attack1type:'Ice',
        attack2name:'Ritual',
        attack2damage:4,
        attack2type:'Holy',
    },
    {
        class:'False Prophet',
        desc:``,
        health:35,
        attack1name:'Poisoned Sacrament',
        attack1damage:5,
        attack1type:'Poison',
        attack2name:'"Prayer"',
        attack2damage:5,
        attack2type:'Dark',
    },
    {
        class:'Fire Golem',
        desc:``,
        health:60,
        attack1name:'Flaming rock',
        attack1damage:3,
        attack1type:'Fire',
        attack2name:'Solidify',
        attack2damage:8,
        attack2type:'Block',
    },
    // {
    //     class:'',
    //     desc:``,
    //     health:0,
    //     attack1name:'',
    //     attack1damage:0,
    //     attack1type:'',
    //     attack2name:'',
    //     attack2damage:0,
    //     attack2type:'',
    // },
    
]