// Current Classes:Goblin,Beast,Spectre
// Current Attack Types: Slash, Blunt, Fire, Ice, Holy, Arcane


module.exports = [
    {
        name:'Goblin Fisher',
        class:'Goblin',
        health:15,
        weaknesses:'Slash',
        resistances:'Ice',
        attack1name:'Kick',
        attack1damage:3,
        attack2name:'Punch',
        attack2damage:3,
        xpReward:3,
        scoreReward:20,
    },
    {
        name:'Goblin Archer',
        class:'Goblin',
        health:12,
        weaknesses:'Slash',
        resistances:'Ice',
        attack1name:'Fragile Arrow',
        attack1damage:4,
        attack2name:'Punch',
        attack2damage:2,
        xpReward:3,
        scoreReward:25,
    },
    {
        name:'Goblin Warrior',
        class:'Goblin',
        health:20,
        weaknesses:'Blunt',
        resistances:'Slash',
        attack1name:'Shield-Bash',
        attack1damage:3,
        attack2name:'Headbutt',
        attack2damage:4,
        xpReward:8,
        scoreReward:50,
    },
    {
        name:'Wolf',
        class:'Beast',
        health:15,
        weaknesses:'Fire',
        resistances:'Ice',
        attack1name:'Bite',
        attack1damage:3,
        attack2name:'Claw',
        attack2damage:3,
        xpReward:3,
        scoreReward:25,
    },
    {
        name:'Spider',
        class:'Beast',
        health:12,
        weaknesses:'Fire',
        resistances:'Blunt',
        attack1name:'Bite',
        attack1damage:2,
        attack2name:'Spit Poison',
        attack2damage:4,
        xpReward:5,
        scoreReward:40,
    },
    {
        name:'Tiger',
        class:'Beast',
        health:20,
        weaknesses:'Slash',
        resistances:'Arcane',
        attack1name:'Death Hug',
        attack1damage:6,
        attack2name:'Chomp',
        attack2damage:4,
        xpReward:10,
        scoreReward:80,
    },
    {
        name:'Ghost',
        class:'Spectre',
        health:15,
        weaknesses:'Holy',
        resistances:'Arcane',
        attack1name:'Curse',
        attack1damage:3,
        attack2name:'Possessed-Dagger',
        attack2damage:4,
        xpReward:4,
        scoreReward:40,
    },
    {
        name:'Possessed Armor',
        class:'Spectre',
        health:25,
        weaknesses:'Arcane',
        resistances:'Slash',
        attack1name:'Shield-Bash',
        attack1damage:3,
        attack2name:'Decapitate',
        attack2damage:5,
        xpReward:12,
        scoreReward:120,
    },
    {
        name:'',
        class:'',
        health:0,
        weaknesses:'',
        resistances:'',
        attack1name:'',
        attack1damage:0,
        attack2name:'',
        attack2damage:0,
        xpReward:0,
        scoreReward:0,
    },
   
]